"""Constants for the Zonneplan ONE integration."""

from homeassistant.const import (
    DEVICE_CLASS_ENERGY,
    DEVICE_CLASS_POWER,
    DEVICE_CLASS_TIMESTAMP,
    ENERGY_KILO_WATT_HOUR,
    POWER_WATT,
    VOLUME_CUBIC_METERS,
)

DOMAIN = "zonneplan_one"


"""Available sensors"""
SENSOR_TYPES = {
    # Inverter
    "highest_measured_power_value": {
        "type": "pv_installation",
        "key": "pv_installation.meta.highest_measured_power_value",
        "label": "highest yield value",
        "unit": POWER_WATT,
        "device_class": DEVICE_CLASS_POWER,
        "icon": "mdi:solar-power",
    },
    "highest_power_measured_at": {
        "type": "pv_installation",
        "key": "pv_installation.meta.highest_power_measured_at",
        "label": "highest yield",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar",
    },
    "total_power_measured": {
        "type": "pv_installation",
        "key": "pv_installation.meta.total_power_measured",
        "label": "yield total",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "icon": "mdi:solar-power",
        "default_enabled": True,
    },
    "last_measured_power_value": {
        "type": "pv_installation",
        "key": "pv_installation.meta.last_measured_power_value",
        "label": "last measured value",
        "unit": POWER_WATT,
        "device_class": DEVICE_CLASS_POWER,
        "icon": "mdi:solar-power",
        "default_enabled": True,
    },
    "first_measured_at": {
        "type": "pv_installation",
        "key": "pv_installation.meta.first_measured_at",
        "label": "first measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
    },
    "last_measured_at": {
        "type": "pv_installation",
        "key": "pv_installation.meta.last_measured_at",
        "label": "last measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
        "default_enabled": True,
    },
    "total_today": {
        "type": "pv_installation",
        "key": "live_data.total",
        "label": "yield today",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "icon": "mdi:solar-power",
        "default_enabled": True,
    },
    # P1
    "electricity_total_today": {
        "type": "p1_installation",
        "key": "electricity.measurement_groups.0.total",
        "label": "electricity consumption today",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "default_enabled": True,
    },
    "electricity_total_today_low_tariff": {
        "type": "p1_installation",
        "key": "electricity.measurement_groups.0.meta.low_tariff_group",
        "label": "electricity consumption today low tariff",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "default_enabled": False,
    },
    "electricity_total_today_normal_tariff": {
        "type": "p1_installation",
        "key": "electricity.measurement_groups.0.meta.normal_tariff_group",
        "label": "electricity consumption today normal tariff",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "default_enabled": False,
    },
    "electricity_total_today_high_tariff": {
        "type": "p1_installation",
        "key": "electricity.measurement_groups.0.meta.high_tariff_group",
        "label": "electricity consumption today high tariff",
        "unit": ENERGY_KILO_WATT_HOUR,
        "device_class": DEVICE_CLASS_ENERGY,
        "default_enabled": False,
    },
    "electricity_last_measured_delivery_value": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_last_measured_delivery_value",
        "label": "electricity consumption",
        "unit": POWER_WATT,
        "device_class": DEVICE_CLASS_POWER,
        "default_enabled": True,
    },
    "electricity_last_measured_production_value": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_last_measured_production_value",
        "label": "electricity production",
        "unit": POWER_WATT,
        "device_class": DEVICE_CLASS_POWER,
        "default_enabled": True,
    },
    "electricity_last_measured_average_value": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_last_measured_average_value",
        "label": "electricity average",
        "unit": POWER_WATT,
        "device_class": DEVICE_CLASS_POWER,
        "default_enabled": True,
    },
    "electricity_first_measured_at": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_first_measured_at",
        "label": "electricity first measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
    },
    "electricity_last_measured_at": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_last_measured_at",
        "label": "electricity last measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
        "default_enabled": True,
    },
    "electricity_last_measured_production_at": {
        "type": "p1_installation",
        "key": "p1_installation.meta.electricity_last_measured_production_at",
        "label": "electricity last measured production",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
        "default_enabled": True,
    },
    "gas_total_today": {
        "type": "p1_installation",
        "key": "gas.measurement_groups.0.total",
        "label": "gas consumption today",
        "unit": VOLUME_CUBIC_METERS,
        "icon": "mdi:fire",
        "default_enabled": True,
    },
    "gas_last_measured_value": {
        "type": "p1_installation",
        "key": "p1_installation.meta.gas_last_measured_value",
        "label": "gas last measured consumption",
        "unit": VOLUME_CUBIC_METERS,
        "icon": "mdi:fire",
        "default_enabled": True,
    },
    "gas_first_measured_at": {
        "type": "p1_installation",
        "key": "p1_installation.meta.gas_first_measured_at",
        "label": "gas first measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
    },
    "gas_last_measured_at": {
        "type": "p1_installation",
        "key": "p1_installation.meta.gas_last_measured_at",
        "label": "gas last measured",
        "device_class": DEVICE_CLASS_TIMESTAMP,
        "icon": "mdi:calendar-clock",
        "default_enabled": True,
    },
}